const money = n => `$${Number(n).toFixed(4)}`;
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(path){const response=await fetch(path);return response.json()}
async function loadAll(){
  const [metrics,runs,approvals,audit]=await Promise.all([get('/api/v1/metrics'),get('/api/v1/runs'),get('/api/v1/approvals'),get('/api/v1/audit')]);
  document.querySelector('#metrics').innerHTML=[['Runs',metrics.runs],['Failure rate',metrics.failureRate+'%'],['Avg. latency',metrics.averageLatencyMs+' ms'],['Token volume',metrics.tokens.toLocaleString()],['Est. cost',money(metrics.estimatedCostUsd)]].map(([label,value])=>`<div class="metric"><label>${label}</label><strong>${value}</strong></div>`).join('');
  document.querySelector('#runs').innerHTML=runs.items.map(run=>`<tr class="clickable" onclick="showTrace('${run.id}')"><td><strong>${escape(run.agent_name)}</strong><br><span class="muted">${escape(run.trace_id)}</span></td><td class="${run.status}">${escape(run.status)}</td><td>${escape(run.model)}<br><span class="muted">${escape(run.prompt_version)}</span></td><td>${run.latency_ms} ms</td><td>${money(run.estimated_cost_usd)}</td><td><span class="badge">${escape(run.risk_level)}</span></td></tr>`).join('');
  document.querySelector('#approvals').innerHTML=approvals.items.length?approvals.items.map(approval=>`<div class="approval"><strong>${escape(approval.tool_name)}</strong> <span class="badge">${escape(approval.risk_level)}</span><div class="muted">${escape(approval.agent_name)} · ${escape(approval.trace_id)} · ${escape(approval.status)}</div>${approval.status==='pending'?`<div class="actions"><button class="approve" onclick="decide('${approval.id}','approved')">Approve</button><button class="reject" onclick="decide('${approval.id}','rejected')">Reject</button></div>`:''}</div>`).join(''):'<p class="muted">No approvals yet.</p>';
  document.querySelector('#audit').innerHTML=audit.items.slice(0,5).map(event=>`<div class="audit"><strong>${escape(event.event_type)}</strong><div class="muted">${escape(event.actor)} · ${new Date(event.created_at).toLocaleString()}</div></div>`).join('');
}
async function decide(id,decision){const note=prompt('Decision note (optional):')??'';await fetch(`/api/v1/approvals/${id}/decision`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision,note})});loadAll()}
async function showTrace(id){const run=await get(`/api/v1/runs/${id}`);document.querySelector('#trace').innerHTML=`<p class="eyebrow">TRACE ${escape(run.trace_id)}</p><h2>${escape(run.agent_name)}</h2>${run.trace.map(span=>`<div class="trace-item ${span.parent_run_id?'child':''}"><strong>${escape(span.agent_name)}</strong> · <span class="${span.status}">${escape(span.status)}</span><div class="muted">${span.parent_run_id?'child span · ':''}${escape(span.tool_name||'no tool')} · ${span.latency_ms} ms · ${span.input_tokens+span.output_tokens} tokens${span.error_message?' · '+escape(span.error_message):''}</div></div>`).join('')}`;traceDialog.showModal()}
loadAll();
